### PR TITLE
Add editorconfig

### PR DESCRIPTION
**Pull request by hugodahl**
This PR is to address reported issue #6.

Add a `.editorconfig` file to the project's root directory, and reformat code files for consistency and have a clean "baseline" of formatted code, rather than haphazard reformats here and there.

The `.editorconfig` file is a copy of the latest version (at this time) of the one from the [csharpfritz/Fritz.StreamTools](https://github.com/csharpfritz/Fritz.StreamTools/blob/25d4dff4ac39c456fc9413f25ccc1a4cb269a1c1/.editorconfig) project.

### CODE REVIEW

**Comment by csharpfritz** [comment]
I just updated the layout of the folders to use a "src" top-level folder for the projects.  Can you back out the second commit and use the updated layout?  That should reduce the conflicts

Thanks

**Comment by hugodahl** [comment]
I've updated the paths and solution so that everything lines up. I've also updated the PR to merge into the `dev` branch.

**Comment by csharpfritz** [comment]
Fantastic!  I'll look at these in Friday's stream


Jeff

**Comment by csharpfritz** [comment]
Thank you for setting this standard for us... much appreciated

**Pull request merged**
