### PR TITLE
changes copying the plugin files to creating a NTFS Junction

### PR DESCRIPTION
**Pull request by Stelzi79**
Removes (commenting out) the copying of the bin files and instead creates a NTFS Junction to the bin folder.

Needs testing - I still don't own a stream deck!

### CODE REVIEW

**Comment by NotMyself** [comment]
This is a pretty cool idea. Are there Windows version constraints to using this? Like do you need Windows 10 Pro or above to create symlinks like this?

**Comment by Stelzi79** [comment]
As I know NTFS junctions are specific to NTFS and a well kept secrete from Windows 2000 (with a server resource kit also on XP) upwards. Please don't use the term "symlink" when talking of junctions on Windows because there is a thing like symlink for directories but are limited in certain usage scenarios. Both can be created by `mklink.exe`.

https://en.wikipedia.org/wiki/NTFS_junction_point explains it nicely. Some restrictions are that certain folders like \Windows can't be reached on junctions on startup which is not a limitation in this usage. \Users, \Programms, \Documents and Settings, etc. can be junctions but I would argue against changing them after setup to junctions. Some low level apps that don't use the by Windows provided file api can have problems with junctions if thy are not fully implementing all NTFS features. Visual Studio has no problems with junctions which is pointing to settings or source files.

This is a little know feature of NTFS because there is no UI for creating it in for example Explorer. There are right click tools which "enable" this feature but in stock Windows it can "only" accessed by `mklink.exe` and a `New-Item` (which triggers UAC in a stock Windows) in PowerShell.

**Comment by csharpfritz** [comment]
Can we move this into a separate script so that its not default behavior?

**Comment by csharpfritz** [comment]
If we don't want to make additional changes to this before  Feb 10

**Comment by Stelzi79** [comment]
Refined and implemented this PR idea better in #102. So this PR is not needed/deprecated.

**Pull request closed without merging**
