### PR TITLE
Added DI friendly system

### PR DESCRIPTION
**Pull request by LuckyNoS7evin**
There was a case sensitivity issue with the `Models` directory which I believe to be fixed

Added the HostingExtensions method ConfigureStreamDeckToolkit to allow for the configuration of StreamDeck command args

Added the DependencyInjectionExtensions method AddStreamDeck which adds the correct singletons, configurations and hosted service to initialise and run the Streamdeck plugin

Added a HostedService which is used as the base runner of the ConnectionManager

Adjustments made to the ActionManager and ConnectionManager to allow for DI and removal of the circular reference which occurred 

Added example DI console plugin and example DI web (kestrel) plugin.

May need to look into adding two new templates.

### CODE REVIEW

**Comment by csharpfritz** [comment]
We need to investigate the test failures on this.... it might be some older references that need to be updated

**Comment by LuckyNoS7evin** [comment]
Oh what? The tests ran previously, maybe a package update. Give me a couple of hours

**Comment by LuckyNoS7evin** [comment]
> Oh what? The tests ran previously, maybe a package update. Give me a couple of hours

Oh I see it the CI build tests the template, I didn't see that bit. I need to look at and upgrade the template

**Comment by csharpfritz** [comment]
Thank you for the update... we should revisit and do more work on the toolkit over the next month or so

**Pull request merged**
