### PR TITLE
Feature/sample property inspector

### PR DESCRIPTION
**Pull request by codingbandit**
Sample property inspector - per the release notes for the beta API - persisting this data will come in the next version.

### CODE REVIEW

**Comment by codingbandit** [comment]
FYI: Template test is failing because it includes a new class introduced to the StreamDeckLib project

**Comment by hugodahl** [comment]
Just adding a comment here to have a link between this PR and Issue #24, because I'm CDO like that.

**Comment by csharpfritz** [comment]
If a new class was added, it should have been picked up by the template build, as it references the local StreamDeckLib.   Hmm..  I need to look into that config

**Comment by codingbandit** [comment]
Ah ok - I thought it was pulling from NPM from the master build or something - I can yank out my templates commit, it was my first time trying to update it, so it is very possible that I did something incorrectly. Let me know :)

**Pull request merged**
